<?xml version="1.0"?>

<!-- ===================================================== -->
<!-- BOOSTMTREE Project File    Apache Ant version 1.10.0  -->
<!-- ===================================================== -->

<project name="BOOSTMTREE Build Suite" basedir="." default="usage">

  <!-- Generic project properties -->
  <property name="project.name" value="BOOSTMTREE Build Suite"/>
  <property name="project.version.token" value="_PROJECT_VERSION_ID_"/>
  <property name="project.version" value="1.5.1"/>
  <property name="project.build.token" value="_PROJECT_BUILD_ID_"/>
  <property name="project.build" value="bld20220309"/>
  <property name="project.pkg.name.token" value="_PROJECT_PACKAGE_NAME_"/>
  <property name="rfsrc.pkg.name.token" value="_RFSRC_PACKAGE_NAME_"/>

  <property name="project.pkg.name"  value="boostmtree"/>
  <property name="rfsrc.pkg.name"  value="randomForestSRC"/>
  <property name="logFile" value="boostmtree.log"/>
  
  
  <property name="http.prefix.token" value="_HTTP_PREFIX_"/>
  <property name="http.prefix" value="http://"/>

  <property environment="env"/>

  <!-- Static Locations -->
  <property name="qacDir" value="docs/quality"/>
  <property name="pkgDir"  value="cran"/>


  <!--
    ========================================================================
    ========================================================================
      Include Internal Common Targets..
    ========================================================================
    ========================================================================
  -->
  <include file="internal.xml"/>


  <!--
    ========================================================================
    ========================================================================
      Internal CRAN targets follow.  Not for end use.
    ========================================================================
    ========================================================================
  -->


  <!--
    ========================================================================
      Internal Target:  Set source tree.
    ========================================================================
  -->
  <target name="setSourceTree" depends="internal.init,internal.testSourceTree">
    <property name="bldDir" value="../build"/>
  </target>


  <!--
    ========================================================================
      Internal Target:  Prepare the CRAN output directories
    ========================================================================
  -->
  <target name="prepare" depends="setSourceTree,internal.osPrep">

    <mkdir dir="${bldDir}"/>
    <mkdir dir="${bldDir}/quality"/>
    <mkdir dir="${bldDir}/quality/data"/>

    <mkdir dir="${bldDir}/quality/benchmark"/>
    <mkdir dir="${bldDir}/quality/output"/>

    <copy file="bench.xml" todir="${bldDir}"/>
    <copy file="internal.xml" todir="${bldDir}"/>
    <move file="${bldDir}/bench.xml" tofile="${bldDir}/build.xml"/>
    <replace file="${bldDir}/build.xml" token="${project.version.token}" value="${project.version}"/>
    <replace file="${bldDir}/build.xml" token="${project.build.token}" value="${project.build}"/>
    <replace file="${bldDir}/build.xml" token="${project.build.token}" value="${project.build}"/>

    <copy file="docs/build.properties" todir="${bldDir}"/>

  </target>


  <!--
    ========================================================================
      Internal Target:  Copy the supporting CRAN files to the build tree.
    ========================================================================
  -->
  <target name="quality" depends="prepare,source-package">
    <copy todir="${bldDir}/quality/data">
      <fileset dir="${pkgDir}/data">
        <include name="*.txt"/>
        <include name="*.csv"/>
      </fileset>
    </copy>

    <copy todir="${bldDir}/quality/data">
      <fileset dir="${qacDir}/data">
        <include name="*.txt"/>
        <include name="*.rda"/>
      </fileset>
    </copy>


    <copy todir="${bldDir}/quality">
      <fileset dir="${qacDir}">
        <include name="*.R"/>
      </fileset>
      <filterchain>
        <tokenfilter>
          <replacestring from="${project.pkg.name.token}" to="${project.pkg.name}"/>
        </tokenfilter>
      </filterchain>
    </copy>

    <copy todir="${bldDir}/quality/benchmark">
      <fileset dir="${qacDir}/benchmark">
        <include name="*.txt"/>
        <include name="*.csv"/>
      </fileset>
    </copy>


    <replace file="${bldDir}/quality/load.R" token="_PROJECT_LIBRARY_NAME_" value="${project.pkg.name}${sharedObjectExtension}"/>
    <replace file="${bldDir}/quality/load.R" token="_PROJECT_ARCH_TYPE_" value="${Rlib}"/>
    <replace file="${bldDir}/quality/load.R" token="_PROJECT_SUPPORT_OPENMP_" value="${openMPswitch}"/>

    <replace file="${bldDir}/quality/load.R" token="${project.version.token}" value="${project.version}"/>
    <replace file="${bldDir}/quality/load.R" token="${project.build.token}" value="${project.build}"/>

    <echo file="${bldDir}/quality/generic${scriptExtension}" append="false">${scriptFileCommentLine}
R ${Rarch} CMD BATCH --no-restore --no-save generic.R output${sep}${logFile}
${scriptFileExitLine}
    </echo>

    <!--
       TBD TBD TBD  Bivariate Boosting Benchmarks TBD TBD TBD
    -->

    <chmod dir="${bldDir}/quality" perm="u+rwx" includes="*${scriptExtension}" os="Linux,Mac OS X,SunOS"/>

  </target>

  

  <!--
    ========================================================================
      Internal target, source-package
    ========================================================================
  -->
  <target name="source-package" depends="setSourceTree">

    <mkdir  dir="${bldDir}"/>
    <mkdir  dir="${bldDir}/cran"/>
    <mkdir  dir="${bldDir}/cran/${project.pkg.name}"/>
    <mkdir  dir="${bldDir}/cran/${project.pkg.name}/inst"/>
    <mkdir  dir="${bldDir}/cran/${project.pkg.name}/data"/>
    <mkdir  dir="${bldDir}/cran/${project.pkg.name}/man"/>
    <mkdir  dir="${bldDir}/cran/${project.pkg.name}/R"/>

    <copy todir="${bldDir}/cran/${project.pkg.name}/R">
      <fileset dir="${pkgDir}/R">
        <include name="*.R"/>
      </fileset>

      <filterchain>
        <fixcrlf eol="lf"/>
      </filterchain>
      <filterchain>
        <replacestring from="##" to="//"/>
        <stripjavacomments/>
        <tokenfilter>
            <ignoreblank/>
        </tokenfilter>
      </filterchain>

      <filterchain>
        <concatfilter prepend="${pkgDir}/copyright"/>
        <tokenfilter>
          <replacestring from="${project.pkg.name.token}" to="${project.pkg.name}"/>
          <replacestring from="${project.version.token}" to="${project.version}"/>
          <replacestring from="////" to="####"/>
        </tokenfilter>
      </filterchain>

      <filterchain>
        <fixcrlf eol="lf"/>
      </filterchain>

    </copy>

    <copy todir="${bldDir}/cran/${project.pkg.name}/man">
      <fileset dir="${pkgDir}/man">
        <include name="*.Rd"/>
      </fileset>

      <filterchain>
        <fixcrlf eol="lf"/>
      </filterchain>
      <filterchain>
        <stripjavacomments/>
      </filterchain>

      <filterchain>
        <tokenfilter>
          <replacestring from="${http.prefix.token}" to="${http.prefix}"/>
        </tokenfilter>
      </filterchain>

      <filterchain>
        <tokenfilter>
          <replacestring from="${project.pkg.name.token}" to="${project.pkg.name}"/>
        </tokenfilter>
      </filterchain>

    </copy>


    <copy file="${pkgDir}/NAMESPACE" todir="${bldDir}/cran/${project.pkg.name}">
      <filterchain>
        <tokenfilter>
          <replacestring from="${project.pkg.name.token}" to="${project.pkg.name}"/>
          <replacestring from="${rfsrc.pkg.name.token}" to="${rfsrc.pkg.name}"/>
        </tokenfilter>
      </filterchain>

      <filterchain>
        <stripjavacomments/>
      </filterchain>
    </copy>

    <copy file="${pkgDir}/inst/CITATION" todir="${bldDir}/cran/${project.pkg.name}/inst/"/>
    <replace file="${bldDir}/cran/${project.pkg.name}/inst/CITATION" token="${project.pkg.name.token}" value="${project.pkg.name}"/>

    <copy file="${pkgDir}/DESCRIPTION" todir="${bldDir}/cran/${project.pkg.name}">
      <filterchain>
        <tokenfilter>
          <replacestring from="${project.pkg.name.token}" to="${project.pkg.name}"/>
          <replacestring from="${project.version.token}"  to="${project.version}"/>
          <replacestring from="_PROJECT_DSTAMP_"          to="${DSTAMP}"/>
          <replacestring from="${rfsrc.pkg.name.token}" to="${rfsrc.pkg.name}"/>
        </tokenfilter>
      </filterchain>
    </copy>
    
    <copy file="${pkgDir}/inst/NEWS" todir="${bldDir}/cran/${project.pkg.name}/inst">
      <filterchain>
        <tokenfilter>
          <replacestring from="${project.pkg.name.token}" to="${project.pkg.name}"/>
          <replacestring from="${project.version.token}" to="${project.version}"/>
          <replacestring from="${project.build.token}" to="${project.build}"/>
        </tokenfilter>
      </filterchain>
    </copy>

    <!--
      Compress Data Files ...
    -->

    <mkdir dir="${bldDir}/cran/staged"/>
    <copy file="docs/scripts/compressData.R" todir="${bldDir}/cran/staged"/>

    <copy todir="${bldDir}/cran/staged">
      <fileset dir="${pkgDir}/data">
        <include name="*.txt"/>
        <include name="*.csv"/>
        <include name="*.RData"/>
      </fileset>
    </copy>

    <exec dir="${bldDir}/cran/staged" executable="R" failonerror="TRUE">
      <arg line="CMD BATCH --no-restore --no-save "/>
      <arg line="compressData.R"/>
      <arg line="compressData.log"/>
    </exec>

    <copy todir="${bldDir}/cran/${project.pkg.name}/data">
      <fileset dir="${bldDir}/cran/staged">
        <include name="*.RData"/>
      </fileset>
    </copy>

    <delete dir="${bldDir}/cran/staged" />

    <copy todir="${bldDir}/cran/${project.pkg.name}/data">
      <fileset dir="${pkgDir}/data">
        <include name="*.RData"/>
      </fileset>
    </copy>

  </target>

  
  
  <!--
    ========================================================================
      Internal target:  package-generic
    ========================================================================
  -->
  <target name="package-generic" depends="clean,internal.osPrep,internal.setCranLibs,source-package">


    <exec dir="${bldDir}/cran" executable="R" failonerror="TRUE">
      <arg line="CMD check"/>
      <arg line="--as-cran"/>
      <arg line="${project.pkg.name}"/>
    </exec>

    <exec dir="${bldDir}/cran" executable="R" failonerror="TRUE">
      <arg line="CMD build"/>
      <arg line="--resave-data"/>
      <arg line="${project.pkg.name}"/>
    </exec>
  </target>

  <!--
    ========================================================================
      Internal target:  install-generic
    ========================================================================
  -->
  <target name="install-generic" depends="setSourceTree,internal.osPrep,internal.setCranLibs">
    <exec dir="${bldDir}/cran" executable="R" failonerror="TRUE">
      <arg line="CMD INSTALL"/>
      <arg line="--clean"/>
      <arg line="--preclean"/>
      <arg line="--build"/>
      <arg line="${project.pkg.name}"/>
    </exec>
  </target>

  <!--
    ========================================================================
      Internal target, serial-XX-generic
    ========================================================================
  -->
  <target name="serial-64-generic" depends="internal.setSerial64,quality"/>



  
  <!--
    ========================================================================
      External SOURCE CRAN targets follow.
    ========================================================================
  -->

  <!--
    ========================================================================
      CLEAN target, Entry Point
    ========================================================================
  -->
  <target name="clean" depends="setSourceTree">
    <delete dir="${bldDir}"/>
  </target>

  
  <!--
    ========================================================================
      SOURCE target, Entry Point
    ========================================================================
  -->
  <target name="source" depends="setSourceTree">
    <mkdir dir="${bldDir}"/>
    <mkdir dir="${bldDir}/cran"/>
    <zip destfile="${bldDir}/cran/boostmtree.${project.build}.zip"
         basedir="../"
         includes="boostmtree/**"
         excludes=""/>
    <tar destfile="${bldDir}/cran/boostmtree.${project.build}.tar"
         basedir="../"
         includes="boostmtree/**"
         excludes=""/>
  </target>


  <!--
    ========================================================================
      PACKAGE target, Entry Point
    ========================================================================
  -->
  <target name="package" depends="package-generic"/>

  
  <!--
    ========================================================================
      INSTALL target, Entry Point
    ========================================================================
  -->
  <target name="install" depends="install-generic"/>

  
 <!--
    ========================================================================
      PACKAGE-AND-INSTALL target, Entry Point
    ========================================================================
  -->
  <target name="package-and-install"     depends="package, install, serial"/>

  
  <!--
    ========================================================================
      SERIAL-XX target, DEFAULT Entry Point
    ========================================================================
  -->
  <target name="serial"        depends="serial-64-generic"/>

  <!--
    ========================================================================
      Help on usage.  List available targets
    ========================================================================
    -->
  <target name="usage" depends="internal.init">
    <echo message=""/>
    <echo message=" Available targets are:"/>
    <echo message=""/>
    <echo message=" clean"/>
    <echo message="     --> delete the build tree"/>
    <echo message=""/>
    <echo message=" source"/>
    <echo message="     --> generate a tar/zip file of the source tree"/>
    <echo message=""/>
    <echo message=" package"/>
    <echo message="     --> generate the CRAN source package"/>
    <echo message=""/>
    <echo message=" install"/>
    <echo message="     --> install the CRAN serial package"/>
    <echo message=""/>
    <echo message=" package-and-install"/>
    <echo message="     --> package and install the CRAN serial package"/>
    <echo message=""/>
    <echo message=" serial"/>
    <echo message="     --> build using 64-bit serial compiler"/>
    <echo message=""/>
  </target>

</project>



