############################################
# Ant framework internal properties file.  #
# DO NOT copy or modify this file.         #
# You shouldn't even be looking at it.     #
############################################
buildTree = TRUE
